### ISSUE TITLE
Log shows "shutdown" and 5 lines of ""Playing NAME.mp3" every message recieved

### ISSUE THREAD

**Issue by eslachance** [JhonforgeGaming/Music-Bot#1]
My console is being flooded with this every time a message is sent to any channel on any server: 

```
Shutdown...
Playing NAME.mp3
Playing NAME.mp3
Playing NAME.mp3
Playing NAME.mp3
Playing NAME.mp3
```

**Comment by ScarlettJFG** [comment]
Thats because it runs .MP3 files form YOUR PC. you have to set the paths.

**Comment by bwpikaard** [comment]
Nah...it's because you put the console.log out of the if statement. 😛

**Comment by ScarlettJFG** [comment]
change console.log in the code to represent the song you set with the filepath.

**Comment by bwpikaard** [comment]
That still has nothing to do with it.

**Comment by ScarlettJFG** [comment]
I re-uploaded the code. this is what I have but it only works for me without edits. For this issue change `console.log("Playing FILENAME.mp3")` to `console.log("Playing songOfYourChoosing")`

**Comment by funcdoor** [comment]
the console.log statements are still outside of the if statements, causing them to all trigger

**Comment by ScarlettJFG** [comment]
very true...I should fix that...brb
fixed

**Comment by funcdoor** [comment]
It's not fixed, it still will print the "Shutdown?" message on every incoming message

I suggest you actually try running your own bot rather than just hoping for the best

**Comment by ScarlettJFG** [comment]
I actually do https://discord.gg/RKtBxzF I have tested it. Although I will admit I did ignore that stuff. I tend to put that there so that if it errors I know where it errors. 

Also please don't suggest that I don't test my own bots. I run them on the laptop I take pretty much everywhere with me. While I don't mean to be someone that makes things people don't understand sometimes it happens. And Voila it is ALL fixed.
